# Generated by Django 3.2.23 on 2023-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0016_add_aws_sse_kms_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3exportstorage',
            name='is_export_csv',
            field=models.BooleanField(blank=True, help_text='Export csv to storage enabled', null=True, verbose_name='is_export_csv'),
        ),
    ]
